# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qAeroChart
                                 A QGIS plugin
 ICAO Aeronautical Chart Plugin - Create approach profiles and aeronautical charts
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-21
        copyright            : (C) 2025 by andures
        email                : your.email@example.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QAeroChart class from file qaerochart.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qaerochart import QAeroChart
    return QAeroChart(iface)
